services:
  weaviate:
    image: semitechnologies/weaviate:1.24.3
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      QUERY_DEFAULTS_LIMIT: "25"
      DEFAULT_VECTORIZER_MODULE: "text2vec-contextionary"  # Ensure this matches your service below
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always

  text2vec-transformers:
    image: semitechnologies/multi2vec-clip
    restart: always

volumes:
  weaviate_data:


    